### ISSUE TITLE
Pls Deps LoggerService error 404

### ISSUE THREAD

**Issue by aphagon** [drashland/deno-drash-middleware#100]
I think deps.ts runs the old version of Drash 1.3.1.
Can you please fix it to the latest version?

https://deno.land/x/drash_middleware@v0.7.0/deps.ts

**Comment by ebebbington** [comment]
Will be fixed in https://github.com/drashland/deno-drash-middleware/pull/98, going this merge this and make a new release :)

**Comment by aphagon** [comment]
> Will be fixed in #98, going this merge this and make a new release :)

Thanks for the reply,
I just saw an update in the master.

**Comment by ebebbington** [comment]
Released: https://github.com/drashland/deno-drash-middleware/releases/tag/v0.7.1, let us know if this definitely fixed your problem :)

**Comment by aphagon** [comment]
> Released: https://github.com/drashland/deno-drash-middleware/releases/tag/v0.7.1 (you just need to update. your deno.land import), let us know if this definitely fixed your problem :)

Oh Wow!
Thanks a lot. 👍
