### ISSUE TITLE
Paladin - clean up large function

### ISSUE THREAD

**Issue by crookse** [drashland/deno-drash-middleware#27]
## Summary

What:

Paladin's function is large. Break it down.

Why:

Readability for newcomers. We're going with an object of key value pairs so that we can easily see which headers are mapped to which functions. This will also make it easier for newcomers to see what headers are mapped to what functions. See discussion below for more context surrounding this issue.

![Screen Shot 2020-07-17 at 17 39 30](https://user-images.githubusercontent.com/12766301/87832703-9a508e00-c854-11ea-9a66-0f2e4bd375c9.png)

## Acceptance Criteria

- [ ] Break down the function into smaller functions
- [ ] Write unit tests

## Taking on this issue? Read this before you get started.

If you take on this issue and the acceptance criteria does not make sense, post comments on this issue with your questions. Also, you can always hop in the Discord channel at https://discord.gg/c5R3sYuR to get help quickly.

Please read the [Contributing Guidelines](https://github.com/drashland/.github/blob/master/CONTRIBUTING.md) before starting this issue.

**Comment by ebebbington** [comment]
The reason why i think this might get messy, is because not all logic for setting headers is as simple as`if config[some-header] then do this`, those those sections (im lookingat you hsts) could be improved

**Comment by ebebbington** [comment]
If anyone does have ideas then feel free to have a play around yourself if you're in the mood for refactoring :P
